"""Generates the Nafir icons: a red nafir (the long Persian horn) on black.

The horn is drawn lying along the x axis around the centre of a 512×512
canvas and then tilted, so the same shapes serve every icon. Writes:

  web/icons/icon.svg                                   app / PWA / favicon
  android/app/src/main/res/drawable/ic_stat_nafir.xml  monochrome notification icon

Android launcher PNGs and assets/icon/nafir.png are rendered from
web/icons/icon.svg (see README).

    python3 tool/generate_icons.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

BACKGROUND = "#000000"
RED = "#E53935"
DARK_RED = "#9E1C1A"
TILT = -35  # degrees; the bell points up and to the right
SCALE = 0.9  # keeps the bell inside the maskable safe zone (radius 205)

# Centre line is y = 256. The mouthpiece is at the left, the bell at the right.
# Half widths: 7 at the mouthpiece end of the tube, 12 where the bell starts,
# 70 at the rim.
HORN = (
    # mouthpiece cup
    "M52 238C64 240 72 247 78 249"
    # tube, slowly widening
    "L330 244"
    # bell flaring out to the rim
    "C382 242 424 222 452 186"
    "L452 326"
    "C424 290 382 270 330 268"
    "L78 263"
    "C72 265 64 272 52 274Z"
)
# Decorative bands on the tube: gaps that show the background through.
BANDS = [(150, 11), (238, 12)]  # (x, half height)
RIM = 'cx="452" cy="256" rx="9" ry="70"'


def transform(scale: float = SCALE) -> str:
    return f"rotate({TILT} 256 256) translate(256 256) scale({scale}) translate(-256 -256)"


def icon_svg() -> str:
    bands = "".join(
        f'<rect x="{x}" y="{256 - h}" width="9" height="{2 * h}" fill="{BACKGROUND}"/>'
        for x, h in BANDS
    )
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">\n'
        f'  <rect width="512" height="512" rx="112" fill="{BACKGROUND}"/>\n'
        f'  <g transform="{transform()}">\n'
        f'    <path fill="{RED}" d="{HORN}"/>\n'
        f"    {bands}\n"
        f'    <ellipse {RIM} fill="{DARK_RED}"/>\n'
        "  </g>\n"
        "</svg>\n"
    )


def notification_xml() -> str:
    # Android draws notification icons in one colour: the silhouette only,
    # a little larger than in the launcher icon.
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tool/generate_icons.py: a nafir silhouette. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp"\n'
        '    android:height="24dp"\n'
        '    android:viewportWidth="512"\n'
        '    android:viewportHeight="512">\n'
        "    <group\n"
        f'        android:rotation="{TILT}"\n'
        '        android:pivotX="256"\n'
        '        android:pivotY="256"\n'
        '        android:scaleX="1.05"\n'
        '        android:scaleY="1.05">\n'
        "        <path\n"
        '            android:fillColor="#FFFFFFFF"\n'
        f'            android:pathData="{HORN}" />\n'
        "    </group>\n"
        "</vector>\n"
    )


def main() -> None:
    (ROOT / "web/icons/icon.svg").write_text(icon_svg(), encoding="utf-8")
    (ROOT / "android/app/src/main/res/drawable/ic_stat_nafir.xml").write_text(
        notification_xml(), encoding="utf-8"
    )


if __name__ == "__main__":
    main()
