"""Generate rhythmo's vector rhythm/play mark and all shipped icon sizes.

Install rendering dependencies with `python3 -m pip install -r tool/icon-requirements.txt`,
then run `python3 tool/generate_icons.py`. Technical asset names stay stable.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKGROUND = "#0B0D16"
PRIMARY = "#FF647C"
# Rounded waveform bars lead into a play triangle. All points lie inside
# the PWA maskable safe circle (centre 256,256; radius 204.8).
MARK = (
    "M132 216C132 208 138 202 146 202C154 202 160 208 160 216"
    "V296C160 304 154 310 146 310C138 310 132 304 132 296Z"
    "M180 176C180 168 186 162 194 162C202 162 208 168 208 176"
    "V336C208 344 202 350 194 350C186 350 180 344 180 336Z"
    "M228 144C228 136 234 130 242 130C250 130 256 136 256 144"
    "V368C256 376 250 382 242 382C234 382 228 376 228 368Z"
    "M296 184C290 180 282 184 282 192V320C282 328 290 332 296 328"
    "L390 264C396 260 396 252 390 248Z"
)


def icon_svg() -> str:
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">\n'
        '  <title>rhythmo</title>\n'
        f'  <rect width="512" height="512" fill="{BACKGROUND}"/>\n'
        f'  <path fill="{PRIMARY}" d="{MARK}"/>\n'
        '</svg>\n'
    )


def notification_xml() -> str:
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tool/generate_icons.py: rhythmo rhythm/play mark. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp" android:height="24dp"\n'
        '    android:viewportWidth="512" android:viewportHeight="512">\n'
        f'  <path android:fillColor="#FFFFFFFF" android:pathData="{MARK}"/>\n'
        '</vector>\n'
    )


def main() -> None:
    import cairosvg

    svg = icon_svg()
    (ROOT / 'web/icons/icon.svg').write_text(svg, encoding='utf-8')
    (ROOT / 'android/app/src/main/res/drawable/ic_stat_nafir.xml').write_text(
        notification_xml(), encoding='utf-8'
    )
    targets = {'assets/icon/nafir.png': 288,
               'web/icons/icon-192.png': 192, 'web/icons/icon-512.png': 512}
    for density, size in [('mdpi', 48), ('hdpi', 72), ('xhdpi', 96),
                          ('xxhdpi', 144), ('xxxhdpi', 192)]:
        targets[f'android/app/src/main/res/mipmap-{density}/ic_launcher.png'] = size
    for path, size in targets.items():
        cairosvg.svg2png(bytestring=svg.encode(), write_to=str(ROOT / path),
                        output_width=size, output_height=size)


if __name__ == '__main__':
    main()
